# Generated by Django 5.1.2 on 2025-03-21 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(max_length=100, verbose_name='Директор фильма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название фильма'),
        ),
        migrations.CreateModel(
            name='Film_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(blank=True, null=True, verbose_name='Год выхода на экран')),
                ('runtime', models.IntegerField(blank=True, null=True, verbose_name='Длительность (мин.)')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр фильма')),
                ('writer', models.CharField(max_length=100, verbose_name='Сценарист')),
                ('actors', models.CharField(max_length=100, verbose_name='Актёры')),
                ('plot', models.TextField(verbose_name='Сюжет')),
                ('language', models.CharField(max_length=100, verbose_name='Язык')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('awards', models.CharField(max_length=100, verbose_name='Призы и награды')),
                ('poster', models.CharField(max_length=100, verbose_name='Ссылка на картинку')),
                ('box_office', models.IntegerField(verbose_name='Бюджет')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='films.film')),
            ],
            options={
                'verbose_name': 'информация о фильме',
                'verbose_name_plural': 'информация о фильмах',
            },
        ),
    ]
