# Generated by Django 5.1.2 on 2025-04-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='film_details',
            name='poster',
            field=models.CharField(max_length=200, verbose_name='Ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(choices=[('драма', 'Драма'), ('комедия', 'Комедия'), ('мелодрама', 'Мелодрама'), ('исторический', 'Исторический'), ('детектив', 'Детектив'), ('криминал', 'Криминал'), ('боевик', 'Боевик'), ('ужасы', 'Ужасы'), ('мюзикл', 'Мюзикл'), ('художественный', 'Художественный'), ('экшн', 'Экшн'), ('фантастика', 'Фантастика')], default='Художественный', max_length=200),
        ),
    ]
