# Generated by Django 5.1.2 on 2025-03-22 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_film_director_alter_film_title_film_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film_details',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Информация', to='films.film'),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('драма', 'Драма'), ('комедия', 'Комедия'), ('мелодрама', 'Мелодрама'), ('исторический', 'Исторический'), ('детектив', 'Детектив'), ('криминал', 'Криминал'), ('боевик', 'Боевик'), ('ужасы', 'Ужасы'), ('мюзикл', 'Мюзикл'), ('художественный', 'Художественный')], default='Художественный', max_length=200)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Жанры', to='films.film')),
            ],
        ),
    ]
