# Generated by Django 5.1.2 on 2025-03-22 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_film_details_film_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
    ]
