# Generated by Django 5.1.2 on 2025-03-22 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_film_options_alter_genre_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film_details',
            name='genre',
        ),
    ]
