# Generated by Django 5.1.2 on 2025-03-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_reviews', '0002_remove_reviews_рейтинг_remove_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
